version: '3.9'
services:
  server:
    build: ./server
    container_name: python_server
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
    environment:
      - FLASK_DEBUG=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/expydb
    depends_on:
      - db
  db:
    build: ./db
    container_name: postgres_db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgressql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=expydb
  client:
    build: ./client
    container_name: react_vite_client
    ports:
      - '5173:5173'
    depends_on:
      - server
