version: '3.9'
services:
  server:
    build: ./server
    # dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
    environment:
      - FLASK_DEBUG=development
  #   depends_on:
  #     - db
  # db:
  #   build:
  #     context: ./services/db
  #     dockerfile: Dockerfile
  #   expose:
  #     - 5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  client:
    build: ./client
    # dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
    depends_on:
      - server
